# Generated by Django 4.2.3 on 2023-07-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_from_old_model(apps, schema_editor):
    JiraIssue = apps.get_model("jira_app", "JiraIssue")
    JiraTicket = apps.get_model("raid", "JiraTicket")

    new_jira_issues = [
        JiraIssue(
            id=old.id,
            key=old.key,
            issue_type=old.issue_type,
            project_key=old.project_key,
            description=old.description,
            summary=old.summary,
            assignee_id=old.assignee_id,
            reporter_id=old.reporter_id,
        )
        for old in JiraTicket.objects.all()
    ]

    JiraIssue.objects.bulk_create(new_jira_issues)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jira_app", "0002_alter_jirauser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraIssue",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=128)),
                ("issue_type", models.CharField(default="Incident", max_length=128)),
                ("project_key", models.CharField(default="INCIDENT", max_length=128)),
                ("description", models.TextField()),
                ("summary", models.CharField(help_text="Title", max_length=128)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_ticket_assigned_set_new",
                        to="jira_app.jirauser",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_ticket_reporter_set_new",
                        to="jira_app.jirauser",
                    ),
                ),
                (
                    "watchers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jira_ticket_watchers_set_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira issue",
                "verbose_name_plural": "Jira issue",
            },
        ),
        migrations.RunPython(
            copy_from_old_model, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO jira_app_jiraissue_watchers (id, jiraissue_id, user_id)
            SELECT id, jiraticket_id, user_id
            FROM raid_jiraticket_watchers;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
