# Generated by Django 4.2.2 on 2023-07-03 11:57
from __future__ import annotations

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.backends.postgresql.schema import DatabaseSchemaEditor


def move_conversation_to_incident_channel(apps, schema_editor: DatabaseSchemaEditor):
    schema_editor.execute(
        """
        INSERT INTO slack_incidentchannel (conversation_ptr_id, incident_new_id)
        SELECT id, incident_id
        FROM slack_conversation
        WHERE incident_id IS NOT NULL
    """
    )

    schema_editor.execute(
        """
        UPDATE slack_conversation
        SET incident_id = NULL
        WHERE incident_id IS NOT NULL
    """
    )


def reverse_move_conversation_to_incident_channel(
    apps, schema_editor: DatabaseSchemaEditor
):
    schema_editor.execute(
        """
        UPDATE slack_conversation
        SET incident_id = slack_incidentchannel.incident_new_id
        FROM slack_incidentchannel
        WHERE slack_conversation.id = slack_incidentchannel.conversation_ptr_id
    """
    )

    schema_editor.execute(
        """
        DELETE FROM slack_incidentchannel
    """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0001_initial_squashed_0022_alter_sos_user_group"),
    ]

    operations: list[
        migrations.DeleteModel
        | migrations.CreateModel
        | migrations.AddField
        | migrations.RunPython
        | migrations.RemoveField
        | migrations.RenameField
        | migrations.AlterField
    ] = [
        migrations.DeleteModel(
            name="IncidentChannel",
        ),
        migrations.CreateModel(
            name="IncidentChannel",
            fields=[
                (
                    "conversation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="slack.conversation",
                    ),
                ),
            ],
            options={
                "proxy": False,
            },
            bases=("slack.conversation",),
        ),
        migrations.AddField(
            model_name="incidentchannel",
            name="incident_new",
            field=models.OneToOneField(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_channel",
                to="incidents.incident",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            move_conversation_to_incident_channel,
            reverse_code=reverse_move_conversation_to_incident_channel,
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="incident",
        ),
        migrations.RenameField(
            model_name="incidentchannel",
            old_name="incident_new",
            new_name="incident",
        ),
        migrations.AlterField(
            model_name="incidentchannel",
            name="incident",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="incidents.incident",
            ),
        ),
    ]
