# Generated by Django 4.1.5 on 2023-02-13 10:16
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("raid", "0001_initial"),
        ("raid", "0002_rename_pagerdutyuser_jirauser"),
        ("raid", "0003_alter_jirauser_id"),
        ("raid", "0004_jiraticket"),
        ("raid", "0005_alter_jiraticket_options_alter_jiraticket_assignee_and_more"),
        ("raid", "0006_jiraticket_incident"),
        ("raid", "0007_alter_jiraticket_assignee_alter_jiraticket_incident"),
        ("raid", "0008_qualifierrotation"),
    ]

    dependencies = [
        ("incidents", "0036_severity_enabled_create_severity_enabled_update_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira user",
                "verbose_name_plural": "Jira users",
            },
        ),
        migrations.CreateModel(
            name="JiraTicket",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=128)),
                (
                    "business_impact",
                    models.CharField(
                        help_text="It maps with customfield_10936", max_length=128
                    ),
                ),
                ("description", models.TextField()),
                ("summary", models.CharField(help_text="Title", max_length=128)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_ticket_assigned_set",
                        to="raid.jirauser",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_ticket_reporter_set",
                        to="raid.jirauser",
                    ),
                ),
                (
                    "watchers",
                    models.ManyToManyField(
                        related_name="jira_ticket_watchers_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_ticket",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira ticket",
                "verbose_name_plural": "Jira tickets",
            },
        ),
        migrations.CreateModel(
            name="QualifierRotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.DateField(unique=True)),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this rotation cannot be automatically changed. Previously `is_modified`.",
                    ),
                ),
                (
                    "jira_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="raid.jirauser"
                    ),
                ),
            ],
        ),
    ]
