# Generated by Django 4.1.7 on 2023-04-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0039_impact_impacttype_incidentimpact_impact_impact_type_and_more",
        ),
        ("raid", "0011_merge_20230408_1956"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraTicketImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.impact",
                    ),
                ),
                (
                    "jira_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raid.jiraticket",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jiraticket",
            name="impacts",
            field=models.ManyToManyField(
                through="raid.JiraTicketImpact", to="incidents.impact"
            ),
        ),
    ]
