# Generated by Django 4.2.3 on 2023-07-17 10:02

import django.db.models.deletion
from django.db import migrations, models


def copy_to_old_model(apps, schema_editor):
    OldJiraUser = apps.get_model("raid", "JiraUser")
    NewJiraUser = apps.get_model("jira_app", "JiraUser")

    old_jira_users = [
        OldJiraUser(id=new.id, user_id=new.user_id) for new in NewJiraUser.objects.all()
    ]
    OldJiraUser.objects.bulk_create(old_jira_users)


class Migration(migrations.Migration):
    dependencies = [
        ("jira_app", "0001_initial"),
        ("raid", "0014_alter_jiraticket_business_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_assigned_set",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_reporter_set",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="qualifierrotation",
            name="jira_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jira_app.jirauser"
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=copy_to_old_model),
        migrations.DeleteModel(
            name="JiraUser",
        ),
    ]
