# Generated by Django 4.2.7 on 2023-11-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jira_app", "0005_alter_jiraissue_assignee"),
        ("raid", "0017_alter_qualifierrotation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualifier",
            name="jira_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="jira_app.jirauser"
            ),
        ),
        migrations.AlterField(
            model_name="qualifierrotation",
            name="protected",
            field=models.BooleanField(
                default=False,
                help_text="If checked, it is because this rotation was previously modified so this date won't be deleted and it can not be unprotected again from here.",
            ),
        ),
    ]
