# Generated by Django 4.1.7 on 2023-02-16 11:43
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raid", "0001_initial_squashed_0008_qualifierrotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="business_impact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="It maps with customfield_10936",
                max_length=128,
            ),
        ),
    ]
