# Generated by Django 4.1.7 on 2023-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("raid", "0010_jiraticket_issue_type_jiraticket_project_key"),
        ("raid", "0010_raidarea"),
    ]

    operations = []
