# Generated by Django 4.1.9 on 2023-06-06 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("raid", "0012_jiraticketimpact_jiraticket_impacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="jira_ticket_watchers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
