# Generated by Django 4.1.9 on 2023-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raid", "0013_alter_jiraticket_watchers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="business_impact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="It maps with customfield_10936",
                max_length=128,
                null=True,
            ),
        ),
    ]
