# Generated by Django 4.2.3 on 2023-07-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_from_jira_issue(apps, schema_editor):
    JiraIssue = apps.get_model("jira_app", "JiraIssue")
    JiraTicket = apps.get_model("raid", "JiraTicket")

    updated_jira_tickets = []
    # It may not be well optimized, but the reverse is a last resort
    for old in JiraIssue.objects.all():
        try:
            new = JiraTicket.objects.get(jiraissue_ptr=old.id)
        except JiraTicket.DoesNotExist:
            continue
        new.key = old.key
        new.issue_type = old.issue_type
        new.project_key = old.project_key
        new.description = old.description
        new.summary = old.summary
        new.assignee_id = old.assignee_id
        new.reporter_id = old.reporter_id
        updated_jira_tickets.append(new)

    JiraTicket.objects.bulk_update(
        updated_jira_tickets,
        [
            "key",
            "issue_type",
            "project_key",
            "description",
            "summary",
            "assignee_id",
            "reporter_id",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("jira_app", "0003_jiraissue"),
        ("raid", "0015_alter_jiraticket_assignee_alter_jiraticket_reporter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jiraticket",
            old_name="id",
            new_name="jiraissue_ptr",
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_assigned_set_new",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="issue_type",
            field=models.CharField(
                default="Incident", max_length=128, blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="key",
            field=models.CharField(max_length=128, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="project_key",
            field=models.CharField(
                default="INCIDENT", max_length=128, blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_reporter_set_new",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="summary",
            field=models.CharField(
                help_text="Title", max_length=128, blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="jira_ticket_watchers_set_new",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, copy_from_jira_issue),
        migrations.RemoveField(
            model_name="jiraticket",
            name="assignee",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="description",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="issue_type",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="key",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="project_key",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="watchers",
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="jiraissue_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="jira_app.jiraissue",
            ),
        ),
    ]
