# Generated by Django 4.2.7 on 2023-11-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jira_app", "0005_alter_jiraissue_assignee"),
        ("raid", "0016_remove_jiraticket_assignee_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualifierrotation",
            options={
                "verbose_name": "Qualifiers rotation",
                "verbose_name_plural": "Qualifiers rotation",
            },
        ),
        migrations.AlterField(
            model_name="qualifierrotation",
            name="protected",
            field=models.BooleanField(
                default=True,
                help_text="If true, this rotation cannot be automatically changed. Previously `is_modified`.",
            ),
        ),
        migrations.CreateModel(
            name="Qualifier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jira_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jira_app.jirauser",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualifier",
                "verbose_name_plural": "Qualifiers",
            },
        ),
    ]
