---
site_name: FireFighter Dev Docs
repo_url: https://git.manomano.tech/pulse/incident-management/firefighter
repo_name: pulse/incident-management/firefighter
edit_uri: https://git.manomano.tech/pulse/incident-management/firefighter/edit/master/docs/
dev_addr: "127.0.0.1:9000"
theme:
  name: "material"
  custom_dir: docs/overrides
  logo: assets/logo_firefighter.png
  favicon: assets/FireFighterIcon.png
  features:
    - navigation.instant
    - navigation.expand
    # - navigation.indexes
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://manomano-team.slack.com/archives/C01DNJW8CAK
  generator: false
  analytics:
    provider: plausible
    plausible_domain: pulse.pages-manomano.tech/incident-management/firefighter
    plausible_script_url: https://plausible.ist.manomano.tech/js/script.outbound-links.local.js

copyright: Copyright &copy; 2021-2023 Colibri SAS
watch:
  - src
nav:
  - Home & Guides:
      - Readme: index.md
      - Changelog: CHANGELOG.md
      - Contributing:
          - Contributing/0000-README.md
          - Setup:
              - 1. Environment setup: Contributing/0001-setup-environment.md
              - 2. Slack App Setup: Contributing/0002-setup-slack-app.md
              - 3. Environment Setup (bis): Contributing/0003-setup-finish.md
          - Dev Tooling & Commands: Contributing/development.md
          - Design:
              - Architecture Overview: Contributing/0010-general_architecture.md
              - UI Guidelines: Contributing/ui.md
              - UX Guidelines: Contributing/ux.md
              - Docs Guidelines: Contributing/documentation.md
      - FireFighter Web: https://incidents.manomano.tech/
  - Reference:
      - Django Apps:
          - api: reference/api.md
          - confluence: reference/confluence.md
          - firefighter: reference/firefighter.md
          - incidents: reference/incidents.md
          - pagerduty: reference/pagerduty.md
          - slack: reference/slack.md
          - jira_app: reference/jira_app.md
          - raid: reference/raid.md

markdown_extensions:
  # - mkdocs-click
  - abbr
  - admonition
  - tables
  - codehilite
  - toc:
      permalink: "¤"
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
plugins:
  - section-index
  - search
  - include-markdown
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import sys"
            - "import django"
            - "sys.path.insert(0, os.path.abspath('.'))"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'firefighter.settings')"
            - "django.setup()"
          import:
            - https://docs.python.org/3.11/objects.inv
            - https://docs.celeryq.dev/en/stable/objects.inv
            # - https://slack.dev/python-slack-sdk/objects.inv
            - url: https://docs.djangoproject.com/en/4.2/_objects/
              base_url: https://docs.djangoproject.com/en/4.2/
          paths: [firefighter]  # search packages in the src folder
          options:
            show_root_heading: true
            show_signature_annotations: true
            show_if_no_docstring: false
            separate_signature: true
            line_length: 140
            merge_init_into_class: true
            show_submodules: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
  - git-revision-date

extra_css:
  - css/style.css

validation:
  nav:
    omitted_files: warn
    absolute_links: warn
