---
site_name: FireFighter Docs
site_description: FireFighter is ManoMano's incident management tool, built on top of Slack and Jira, with Django and Python.
site_url: https://manomanotech.github.io/firefighter-incident/

repo_url: https://github.com/ManoManoTech/firefighter-incident
repo_name: ManoManoTech/firefighter-incident
edit_uri: https://github.com/ManoManoTech/firefighter-incident/edit/main/docs/

copyright: Copyright &copy; 2021-2024 Colibri SAS
dev_addr: "127.0.0.1:9000"
site_dir: site
docs_dir: docs

watch:
  - src
  - docs
  - mkdocs.yml
  - README.md
  - scripts

extra_css:
  - css/style.css

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  custom_dir: !relative $docs_dir/overrides
  logo: assets/FireFighterIcon.png
  favicon: assets/FireFighterIcon.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    # - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  generator: false
  version:
    provider: mike
    default:
      - latest
      - dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ManoManoTech/firefighter-incident
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/firefighter-incident/

nav:
  - Home:
      - Home: index.md
      - Roadmap: roadmap.md
      - Changelog: CHANGELOG.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Credits: credits.md
      - License: license.md
      - FAQ: FAQ.md
  - Usage:
      - Integrations: usage/integrations.md
      - Deployment:
          - deploy/00-intro.md
          - Settings:
              - deploy/XX-settings.md
              - deploy/XX-custom-settings.md
          - deploy/XX-auth.md
          - Translation and timezone: deploy/XX-i18n-l10.md
          - deploy/XX-logs-traces.md
          - deploy/XX-tasks.md
          - deploy/XX-support-policy.md

  - Development:
      - contributing/0000-README.md
      - Local Development:
          - 0. Prerequisites: contributing/0000-prerequisites.md
          - 1. Setup environment & app: contributing/0001-setup-environment.md
          - 2. Configure Slack: contributing/0002-setup-slack-app.md
      - Developper Guide & Tools: contributing/development.md
      - Architecture & Design:
          - Architecture Overview: contributing/0010-general_architecture.md
          - UI Guidelines: contributing/ui.md
          - UX Guidelines: contributing/ux.md
          - Docs Guidelines: contributing/documentation.md
      - Developper FAQ: contributing/faq.md

  - Reference:
      - Django Apps:
          - api: reference/api.md
          - confluence: reference/confluence.md
          - firefighter: reference/firefighter.md
          - incidents: reference/incidents.md
          - pagerduty: reference/pagerduty.md
          - slack: reference/slack.md
          - jira_app: reference/jira_app.md
          - raid: reference/raid.md


markdown_extensions:
  abbr: {}
  admonition: {}
  attr_list: {}
  codehilite: {}
  def_list: {}
  tables: {}
  md_in_html: {}
  mdx_truly_sane_lists: {}
  pymdownx.magiclink: {}
  pymdownx.details: {}
  pymdownx.highlight:
    anchor_linenums: true
  pymdownx.inlinehilite: {}
  pymdownx.snippets:
    check_paths: true
    base_path: !relative $docs_dir/..
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  toc:
    permalink: "¤"


plugins:
  - autorefs
  - include-markdown
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
  - git-authors:
      enabled: !ENV [CI, false]
  - markdown-exec
  - search
  - section-index
  - social:
      enabled: !ENV [CI, false]
  - mike:
      canonical_version: "latest"
      version_selector: true
  - redirects:
      redirect_maps:
        contributing.md: contributing/0000-README.md
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import sys"
            - "import django"
            - "sys.path.insert(0, os.path.abspath('.'))"
            - "sys.path.insert(0, os.path.abspath('src'))"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'firefighter.firefighter.settings')"
            - "django.setup()"
          import:
            - https://docs.python.org/3.12/objects.inv
            - https://docs.celeryq.dev/en/stable/objects.inv
            # - https://slack.dev/python-slack-sdk/objects.inv
            - url: https://docs.djangoproject.com/en/4.2/_objects/
              base_url: https://docs.djangoproject.com/en/4.2/
              domains: [std, py]
            - https://manomanotech.github.io/loggia/latest/objects.inv
          paths: [src]  # search packages in the src folder
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            preload_modules: [mkdocstrings]
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
            # show_root_heading: true
            # show_signature_annotations: true
            show_if_no_docstring: false
            # separate_signature: true
            line_length: 140
            # merge_init_into_class: true
            show_submodules: true
            docstring_style: google
            # docstring_options:
            # ignore_init_summary: true
