---
site_name: FireFighter Docs
site_description: FireFighter is ManoMano's incident management tool, built on top of Slack and Jira, with Django and Python.
site_url: https://firefighter-incident.readthedocs.io/en/latest/ # FIXME OSS

repo_url: https://github.com/ManoManoTech/firefighter-incident
repo_name: ManoManoTech/firefighter-incident
edit_uri: https://github.com/ManoManoTech/firefighter-incident/edit/main/docs/

copyright: Copyright &copy; 2021-2023 Colibri SAS
dev_addr: "127.0.0.1:9000"
site_dir: site
docs_dir: docs

watch:
  - src
  - docs
  - mkdocs.yml
  - README.md
  - scripts

extra_css:
  - css/style.css

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  custom_dir: docs/overrides
  logo: assets/logo_firefighter.png
  favicon: assets/FireFighterIcon.png
  features:
    - navigation.instant
    - navigation.expand
    # - navigation.indexes
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  generator: false
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ManoManoTech/firefighter-incident

nav:
  - Home:
      - Home: index.md
      - Roadmap: roadmap.md
      - Changelog: CHANGELOG.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Credits: credits.md
      - License: license.md
  - Usage:
      - Deploy/00-intro.md
      - Deploy/XX-auth.md
      - Deploy/XX-custom-settings.md
      - Deploy/XX-i18n-l10.md
      - Deploy/XX-logs-traces.md
      - Deploy/XX-settings.md
      - Deploy/XX-support-policy.md

  - Reference:
      - Django Apps:
          - api: reference/api.md
          - confluence: reference/confluence.md
          - firefighter: reference/firefighter.md
          - incidents: reference/incidents.md
          - pagerduty: reference/pagerduty.md
          - slack: reference/slack.md
          - jira_app: reference/jira_app.md
          - raid: reference/raid.md

  - Development:
      - Contributing/0000-README.md
      - Setup:
          - 0. Prerequisites: Contributing/0000-prerequisites.md
          - 1. Environment setup: Contributing/0001-setup-environment.md
          - 2. Slack App Setup: Contributing/0002-setup-slack-app.md
          - 3. Environment Setup (bis): Contributing/0003-setup-finish.md
      - Dev Tooling & Commands: Contributing/development.md
      - Design:
          - Architecture Overview: Contributing/0010-general_architecture.md
          - UI Guidelines: Contributing/ui.md
          - UX Guidelines: Contributing/ux.md
          - Docs Guidelines: Contributing/documentation.md
      - FAQ: Contributing/faq.md


markdown_extensions:
  - abbr
  - admonition
  - tables
  - codehilite
  - toc:
      permalink: "¤"
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
plugins:
  - section-index
  - search
  - include-markdown
  - autorefs
  - mike:
      canonical_version: "latest"
      version_selector: true
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import sys"
            - "import django"
            - "sys.path.insert(0, os.path.abspath('.'))"
            - "sys.path.insert(0, os.path.abspath('src'))"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'firefighter.firefighter.settings')"
            - "django.setup()"
          import:
            - https://docs.python.org/3.11/objects.inv
            - https://docs.celeryq.dev/en/stable/objects.inv
            # - https://slack.dev/python-slack-sdk/objects.inv
            - url: https://docs.djangoproject.com/en/4.2/_objects/
              base_url: https://docs.djangoproject.com/en/4.2/
          paths: [src]  # search packages in the src folder
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            preload_modules: [mkdocstrings]
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
            # show_root_heading: true
            # show_signature_annotations: true
            show_if_no_docstring: false
            # separate_signature: true
            line_length: 140
            # merge_init_into_class: true
            show_submodules: true
            docstring_style: google
            # docstring_options:
              # ignore_init_summary: true
  - git-revision-date
  - markdown-exec
