from collections.abc import Callable
from typing import TypeVar

from django_components import component

_TC = TypeVar("_TC", bound=type[component.Component])

class ComponentRegistry:
    def __init__(self) -> None: ...
    def register(
        self, name: str | None = None, component: component.Component | None = None
    ) -> None: ...
    def unregister(self, name: str) -> None: ...
    def get(self, name: str) -> type[component.Component]: ...
    def all(self) -> dict[str, type[component.Component]]: ...
    def clear(self) -> None: ...

registry: ComponentRegistry

def register(name: str) -> Callable[[_TC], _TC]: ...
