# Generated by Django 4.2.3 on 2023-07-17 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jira_app", "0001_initial"),
        ("raid", "0015_alter_jiraticket_assignee_alter_jiraticket_reporter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jirauser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
