# Generated by Django 4.2.3 on 2023-07-17 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jira_app", "0003_jiraissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraissue",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_assigned_set",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="jiraissue",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_ticket_reporter_set",
                to="jira_app.jirauser",
            ),
        ),
        migrations.AlterField(
            model_name="jiraissue",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="jira_ticket_watchers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
