# Generated by Django 3.2.3 on 2021-06-01 13:20

from __future__ import annotations

from django.db import migrations, models

import incidents.models.severity


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_incidentupdate_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentupdate",
            name="severity",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(incidents.models.severity.Severity.get_default),
                to="incidents.severity",
            ),
        ),
    ]
