# Generated by Django 3.2.3 on 2021-06-07 08:53

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0003_alter_incidentupdate_severity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="communications_lead",
            new_name="communication_lead",
        ),
        migrations.RenameField(
            model_name="incidentupdate",
            old_name="communications_lead",
            new_name="communication_lead",
        ),
    ]
