# Generated by Django 3.2.3 on 2021-06-08 12:22

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_alter_incidentupdate_communication_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slack_id",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
