# Generated by Django 3.2.4 on 2021-06-23 15:11

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_alter_user_slack_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
