# Generated by Django 3.2.4 on 2021-06-27 19:55

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_auto_20210625_1721_squashed_0014_alter_severity_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="cachet_id",
        ),
        migrations.AlterField(
            model_name="incident",
            name="pagerduty_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
