# Generated by Django 3.2.4 on 2021-06-28 12:27

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0010_auto_20210627_2155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="cachet_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="slack_id",
        ),
        migrations.AlterField(
            model_name="component",
            name="slack_groups",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
