# Generated by Django 3.2.4 on 2021-07-02 14:34

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0011_auto_20210628_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentupdate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentupdate",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
