# Generated by Django 3.2.5 on 2021-07-16 11:55

from __future__ import annotations

import django.db.migrations.operations.special
from django.db import migrations, models


def add_value(apps, schema_editor):
    # We can't import the Environment model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Environment = apps.get_model("incidents", "environment")
    for environment in Environment.objects.all():
        if environment.name == "Prod":
            environment.value = "PRD"
        else:
            environment.value = environment.name.upper()
        environment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("incidents", "0012_auto_20210702_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="value",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=add_value,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="environment",
            name="value",
            field=models.CharField(max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="component",
            name="on_call",
        ),
        migrations.RenameField(
            model_name="component",
            old_name="slack_groups",
            new_name="slack_conversations",
        ),
    ]
