# Generated by Django 3.2.6 on 2021-08-20 13:34

from __future__ import annotations

import django.utils.timezone
from django.db import migrations, models


def add_value(apps, schema_editor):
    # We can't import the Environment model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IncidentUpdate = apps.get_model("incidents", "incidentupdate")
    for update in IncidentUpdate.objects.all():
        if not update.event_ts:
            update.event_ts = update.created_at
            update.save()


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0014_auto_20210809_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentupdate",
            name="event_ts",
            field=models.DateTimeField(auto_now_add=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=add_value,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="event_ts",
            field=models.DateTimeField(auto_now_add=False, null=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="_status",
            field=models.IntegerField(
                choices=[
                    (10, "Open"),
                    (20, "Investigating"),
                    (30, "Mitigating"),
                    (40, "Mitigated"),
                    (50, "Post-mortem"),
                    (60, "Closed"),
                ],
                db_column="status",
                default=10,
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Open"),
                    (20, "Investigating"),
                    (30, "Mitigating"),
                    (40, "Mitigated"),
                    (50, "Post-mortem"),
                    (60, "Closed"),
                ],
                db_column="status",
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="incidentupdate",
            options={"ordering": ["-event_ts"]},
        ),
        migrations.AddField(
            model_name="incidentupdate",
            name="event_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
