# Generated by Django 3.2.6 on 2021-08-29 14:08

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0016_auto_20210825_1039"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="_time_to_detect",
            new_name="time_to_detect",
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="_time_to_internal_response",
            new_name="time_to_internal_response",
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="_time_to_repair",
            new_name="time_to_repair",
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="_time_to_resolve",
            new_name="time_to_resolve",
        ),
        migrations.AlterField(
            model_name="component",
            name="slack_conversations",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Retrieves users from a comma separated list of conversations, when an incident is created with this component.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="_status",
            field=models.IntegerField(
                choices=[
                    (10, "Open"),
                    (20, "Investigating"),
                    (30, "Mitigating"),
                    (40, "Mitigated"),
                    (50, "Post-mortem"),
                    (60, "Closed"),
                ],
                db_column="status",
                default=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="ignore",
            field=models.BooleanField(
                default=False,
                help_text="An ignored incident can be closed right away. In the future, it won't affect statistics or appear in reports. This is useful for duplicates incidents, or false-positives.",
            ),
        ),
    ]
