# Generated by Django 3.2.6 on 2021-08-30 09:44

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0017_auto_20210829_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentupdate",
            name="_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Open"),
                    (20, "Investigating"),
                    (30, "Mitigating"),
                    (40, "Mitigated"),
                    (50, "Post-mortem"),
                    (60, "Closed"),
                ],
                db_column="status",
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
