# Generated by Django 3.2.9 on 2021-11-12 09:38

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import incidents.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0020_auto_20211104_0951"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", incidents.models.user.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="component",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="incidents.group"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_commander",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="communication_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_communication_lead",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="incidents.component"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="incidents.environment"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="incidents.severity"
            ),
        ),
    ]
