# Generated by Django 3.2.13 on 2022-04-25 10:07

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0021_auto_20211112_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="User fullname. Prefer to set `first_name` and `last_name`, and get `full_name`. ",
                max_length=128,
            ),
        ),
    ]
