# Generated by Django 4.1.2 on 2022-10-31 10:56

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0027_remove_component_slack_conversations"),
        ("incidents", "0028_incident_private_alter_component_order_and_more"),
    ]

    operations = []
