# Generated by Django 4.1.3 on 2022-11-06 16:07

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0029_merge_20221031_1156"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.CheckConstraint(
                check=models.Q(("_status__in", [10, 20, 30, 40, 50, 60])),
                name="incidents_incident__status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentupdate",
            constraint=models.CheckConstraint(
                check=models.Q(("_status__in", [10, 20, 30, 40, 50, 60])),
                name="incidents_incidentupdate__status_valid",
            ),
        ),
    ]
