# Generated by Django 4.1.3 on 2022-11-09 22:17

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0030_status_enum_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentCostType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("default", models.BooleanField(default=False)),
                ("editable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IncidentCostType",
                "verbose_name_plural": "IncidentCostTypes",
            },
        ),
        migrations.CreateModel(
            name="IncidentCost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_cost_set",
                        to="incidents.incidentcosttype",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_cost_set",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "IncidentCost",
                "verbose_name_plural": "IncidentCosts",
            },
        ),
    ]
