# Generated by Django 4.1.3 on 2022-11-22 11:18

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0032_alter_incidentcost_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bot",
            field=models.BooleanField(
                default=False,
                help_text="Used for non-person accounts (e.g. integrations that have bot/shared accounts.",
            ),
        ),
    ]
