# Generated by Django 4.1.3 on 2022-11-23 10:52

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0033_user_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="deploy_warning",
            field=models.BooleanField(
                default=True,
                help_text="If true, a warning will be sent when creating an incident of high severity with this component.",
            ),
        ),
    ]
