# Generated by Django 4.1.4 on 2022-12-26 17:06

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0035_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="severity",
            name="enabled_create",
            field=models.BooleanField(
                default=True,
                help_text="Can you create a new incident with this severity?",
            ),
        ),
        migrations.AddField(
            model_name="severity",
            name="enabled_update",
            field=models.BooleanField(
                default=True, help_text="Can you update an incident to this severity?"
            ),
        ),
        migrations.AlterField(
            model_name="severity",
            name="order",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddConstraint(
            model_name="severity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default",),
                name="unique__default",
            ),
        ),
    ]
