# Generated by Django 4.1.7 on 2023-03-30 14:15
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0037_priority_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.ForeignKey(
                blank=True,
                help_text="Severity (legacy, superseded by priority)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.severity",
            ),
        ),
    ]
