# Generated by Django 4.2.3 on 2023-07-21 08:54

from django.db import migrations, models


def split_emojis(apps, schema_editor):
    ImpactLevel = apps.get_model("incidents", "ImpactLevel")
    ImpactType = apps.get_model("incidents", "ImpactType")
    for impact_level in ImpactLevel.objects.all():
        emoji_from_name = impact_level.name.split(" ")[0][:5].strip()
        impact_level.name = impact_level.name[len(emoji_from_name) :].strip()
        impact_level.emoji = emoji_from_name
        impact_level.save()
    for impact_type in ImpactType.objects.all():
        emoji_from_name = impact_type.name.split(" ")[0][:5].strip()
        impact_type.name = impact_type.name[len(emoji_from_name) :].strip()
        impact_type.emoji = emoji_from_name
        impact_type.save()


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0042_alter_impactlevel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactlevel",
            name="emoji",
            field=models.CharField(default="ℹ️", max_length=5),  # noqa: RUF001
        ),
        migrations.AddField(
            model_name="impacttype",
            name="emoji",
            field=models.CharField(default="ℹ️", max_length=5),  # noqa: RUF001
        ),
        migrations.RunPython(split_emojis, reverse_code=migrations.RunPython.noop),
    ]
