# Generated by Django 4.2.4 on 2023-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0046_dynamic_incident_roles_bis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="commander",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="communication_lead",
        ),
        migrations.AddConstraint(
            model_name="incidentroletype",
            constraint=models.CheckConstraint(
                check=models.Q(("slug__regex", "^[a-z0-9\\_]+$")),
                name="incidents_incidentroletype_slug_check",
            ),
        ),
    ]
