# Generated by Django 4.2.5 on 2023-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0047_incidentroletype_incidents_incidentroletype_slug_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentroletype",
            name="best_practices",
        ),
        migrations.RemoveField(
            model_name="incidentroletype",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="incidentroletype",
            name="responsibilities",
        ),
        migrations.AddField(
            model_name="incidentroletype",
            name="summary_first_person",
            field=models.TextField(
                blank=True,
                help_text="First person version of the summary, used for instance in Slack messages to assignees.",
                null=True,
            ),
        ),
    ]
