# Generated by Django 3.2.3 on 2021-06-07 14:22

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_auto_20210607_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentupdate",
            name="communication_lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communication_lead_for",
                to="incidents.user",
            ),
        ),
    ]
