# Generated by Django 4.2.7 on 2023-12-04 11:09


import logging
import uuid

from django.db import migrations, models
from django.db.models import Q

from firefighter.incidents.models.impact import LevelChoices

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0007_update_component_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactlevel",
            name="emoji",
            field=models.CharField(default="▶", max_length=5),
        ),
        migrations.RemoveConstraint(
          model_name="impactlevel",
          name="incidents_impactlevel_value_valid",
        ),
        migrations.AddConstraint(
          model_name="impactlevel",
          constraint=models.CheckConstraint(
            name="incidents_impactlevel_value_valid",
            check=Q(value__in=LevelChoices.values),
          ),
        ),
        migrations.AlterField(
            model_name="impactlevel",
            name="id",
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
    ]
