# Generated by Django 3.2.4 on 2021-06-25 18:59

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

import firefighter.incidents.models.severity


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0008_auto_20210624_1135"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentupdate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="incident",
            name="_time_to_detect",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="_time_to_internal_response",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="_time_to_resolve",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Open"),
                    (20, "Investigating"),
                    (30, "Fixing"),
                    (40, "Fixed"),
                    (50, "Post Mortem"),
                    (60, "Closed"),
                ],
                db_column="status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commander_for",
                to="incidents.user",
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="communication_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communication_lead_for",
                to="incidents.user",
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.component",
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.user",
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="severity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(
                    firefighter.incidents.models.severity.Severity.get_default
                ),
                to="incidents.severity",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="_time_to_repair",
            field=models.DurationField(
                blank=True, db_column="time_to_repair", null=True
            ),
        ),
        migrations.AlterField(
            model_name="severity",
            name="name",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="component",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="severity",
            name="name",
            field=models.CharField(default="SEVXX", max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="severity",
            name="value",
            field=models.IntegerField(unique=True),
        ),
    ]
