# Generated by Django 3.2.6 on 2021-08-09 08:52

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0013_environment_value_squashed_0017_rename_slack_groups_component_slack_conversations",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incidents.user",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="communication_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incidents.user",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incidents.user",
            ),
        ),
        migrations.RemoveField(model_name="incident", name="slack_channel_id"),
        migrations.RemoveField(model_name="incident", name="pagerduty_id"),
    ]
