# Generated by Django 3.2.6 on 2021-08-25 08:39

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0015_auto_20210820_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="time_to_fix",
            field=models.DurationField(blank=True, db_column="time_to_fix", null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_to_recovery",
            field=models.DurationField(
                blank=True, db_column="time_to_recovery", null=True
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_to_respond",
            field=models.DurationField(
                blank=True, db_column="time_to_respond", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="_time_to_detect",
            field=models.DurationField(
                blank=True, db_column="time_to_detect", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="_time_to_internal_response",
            field=models.DurationField(
                blank=True, db_column="time_to_internal_response", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="_time_to_resolve",
            field=models.DurationField(
                blank=True, db_column="time_to_resolve", null=True
            ),
        ),
    ]
