# Generated by Django 3.2.13 on 2022-06-22 13:59

from __future__ import annotations

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="severity",
            name="reminder_time",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                help_text="Time before an incident without any incident update will receive a reminder.",
            ),
        ),
        migrations.CreateModel(
            name="IncidentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.incident",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="members",
            field=models.ManyToManyField(
                through="incidents.IncidentMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
