# Generated by Django 3.2.13 on 2022-06-28 14:37

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0023_auto_20220622_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentmembership",
            name="inviter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
