# Generated by Django 4.0.8 on 2022-10-18 15:23

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0026_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="If true, incident created with this component won't be communicated, and conversations will be made private. This is useful for sensitive components. In the future, private incidents may be visible only to its members.",
            ),
        ),
    ]
