# Generated by Django 4.0.8 on 2022-10-18 15:53

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0027_component_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="A private incident is not communicated in #tech-incidents, and its created conversation is private. In the future, we may restrict the visibility to incident members only.",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Order of the component in the list. Should be unique per `Group`.",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="If true, incident created with this component won't be communicated, and conversations will be made private. This is useful for sensitive components. In the future, private incidents may be visible only to its members.",
            ),
        ),
    ]
