# Generated by Django 4.2.30 on 2026-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0034_add_incident_dedup_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentcategory",
            name="enabled_create",
            field=models.BooleanField(
                default=True,
                help_text="Can you create a new incident with this incident category? Disable to retire a category without losing the incidents already filed against it.",
            ),
        ),
    ]
