# Generated by Django 4.1.3 on 2022-11-24 17:20

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0034_component_deploy_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True,
                help_text="URL to user avatar. Can be hosted externally.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
