# Generated by Django 4.1.7 on 2023-03-28 13:45
from __future__ import annotations

import datetime
import uuid

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F

import firefighter.incidents.models.priority
import firefighter.incidents.models.severity

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:


def copy_severity_to_priority(apps, schema_editor):
    Priority = apps.get_model("incidents", "Priority")
    Severity = apps.get_model("incidents", "Severity")

    # Fetch all Severity objects
    severities = Severity.objects.all()

    # Create a list of Priority instances with the same field values as the corresponding Severity instances
    priorities = [
        Priority(
            id=severity.id,
            name=severity.name.replace("SEV", "P"),
            value=severity.value,
            emoji=severity.emoji,
            description=severity.description,
            order=severity.order,
            default=severity.default,
            needs_postmortem=severity.needs_postmortem,
            enabled_create=severity.enabled_create,
            enabled_update=severity.enabled_update,
            reminder_time=severity.reminder_time,
            created_at=severity.created_at,
            updated_at=severity.updated_at,
        )
        for severity in severities
    ]

    # Bulk create Priority instances
    Priority.objects.bulk_create(priorities)


def add_priority_to_all_incidents_and_updatesty(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    IncidentUpdate = apps.get_model("incidents", "IncidentUpdate")

    # Update the 'priority_id' with the 'severity_id' for all incident + updates
    Incident.objects.update(priority_id=F("severity_id"))
    IncidentUpdate.objects.update(priority_id=F("severity_id"))


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0036_severity_enabled_create_severity_enabled_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("value", models.IntegerField(unique=True)),
                ("emoji", models.CharField(default="🔥", max_length=5)),
                ("description", models.CharField(max_length=128)),
                ("order", models.IntegerField(default=0, unique=True)),
                ("default", models.BooleanField(default=False)),
                ("needs_postmortem", models.BooleanField(default=False)),
                (
                    "enabled_create",
                    models.BooleanField(
                        default=True,
                        help_text="Can you create a new incident with this priority?",
                    ),
                ),
                (
                    "enabled_update",
                    models.BooleanField(
                        default=True,
                        help_text="Can you update an incident to this priority?",
                    ),
                ),
                (
                    "reminder_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600),
                        help_text="Time before an incident without any incident update will receive a reminder.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "priorities",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="priority",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default",),
                name="unique_priority_default",
            ),
        ),
        migrations.RunPython(
            code=copy_severity_to_priority,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="severity",
            options={
                "ordering": ["order"],
                "verbose_name": "severity (legacy)",
                "verbose_name_plural": "severities (legacy)",
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="priority",
            field=models.ForeignKey(
                help_text="Priority",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.priority",
            ),
        ),
        migrations.AddField(
            model_name="priority",
            name="sla",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                help_text="Service Level Agreement",
                verbose_name="SLA",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.ForeignKey(
                help_text="Severity (legacy, superseded by priority)",
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.severity",
            ),
        ),
        migrations.AddField(
            model_name="incidentupdate",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(
                    firefighter.incidents.models.priority.Priority.get_default
                ),
                to="incidents.priority",
            ),
        ),
        migrations.AlterField(
            model_name="incidentupdate",
            name="severity",
            field=models.ForeignKey(
                blank=True,
                help_text="Superseded by priority",
                null=True,
                on_delete=models.SET(
                    firefighter.incidents.models.severity.Severity.get_default
                ),
                to="incidents.severity",
            ),
        ),
        migrations.RunPython(
            code=add_priority_to_all_incidents_and_updatesty,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.ForeignKey(
                help_text="Priority",
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.priority",
            ),
        ),
    ]
