# Generated by Django 4.2.30 on 2026-09-01 09:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0037_link_foundations_slack_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="priority",
            name="postmortem_reminder_repeat_time",
            field=models.DurationField(
                default=datetime.timedelta(days=2),
                help_text="Time without any progress before that reminder is sent again. Set to 0 to remind only once.",
            ),
        ),
        migrations.AddField(
            model_name="priority",
            name="postmortem_reminder_time",
            field=models.DurationField(
                default=datetime.timedelta(days=2),
                help_text="Time after mitigation before the incident channel is reminded that the incident still has to be driven to closure (post-mortem completed, or key events submitted and incident closed).",
            ),
        ),
    ]
