# Generated by Django 4.1.7 on 2023-04-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0039_impact_impacttype_incidentimpact_impact_impact_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="priority",
            name="recommended_response_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
