# Generated by Django 4.2.2 on 2023-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0041_impactlevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactlevel",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
