# Generated by Django 4.2.5 on 2023-09-05 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0048_remove_incidentroletype_best_practices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentrole",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incidentrole",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
