# Generated by Django 4.2.6 on 2023-10-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0049_incidentrole_created_at_incidentrole_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incidentrole",
            name="unique_incident_role",
        ),
        migrations.RenameField(
            model_name="incidentrole",
            old_name="role",
            new_name="role_type",
        ),
        migrations.AddConstraint(
            model_name="incidentrole",
            constraint=models.UniqueConstraint(
                fields=("incident", "user", "role_type"), name="unique_incident_role"
            ),
        ),
    ]
