from slack_sdk.web import SlackResponse

class SlackClientError(Exception): ...
class BotUserAccessError(SlackClientError): ...
class SlackRequestError(SlackClientError): ...

class SlackApiError(SlackClientError):
    response: SlackResponse
    def __init__(self, message: str, response: SlackResponse) -> None: ...

class SlackTokenRotationError(SlackClientError):
    api_error: SlackApiError
    def __init__(self, api_error: SlackApiError) -> None: ...

class SlackClientNotConnectedError(SlackClientError): ...
class SlackObjectFormationError(SlackClientError): ...
class SlackClientConfigurationError(SlackClientError): ...
