# Generated by Django 4.1.9 on 2023-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confluence", "0001_squashed_0007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runbook",
            name="service_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="runbook",
            name="service_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="runbook",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
