# Generated by Django 4.2.6 on 2023-10-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confluence", "0008_alter_runbook_service_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confluencepage",
            name="version",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="confluencepage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When was the DB record created, not when the page was created on Confluence.",
            ),
        ),
        migrations.AlterField(
            model_name="confluencepage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When was the DB record updated, not when the page was created on Confluence.",
            ),
        ),
    ]
