# Generated by Django 4.1.9 on 2023-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagerduty", "0001_squashed_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagerdutyservice",
            name="pagerduty_id",
            field=models.CharField(
                db_index=True,
                help_text="PagerDuty ID for the service.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
