from __future__ import annotations

from firefighter.firefighter.settings.settings_utils import config

RAID_DEFAULT_JIRA_QRAFT_USER_ID: str = config("RAID_DEFAULT_JIRA_QRAFT_USER_ID")
RAID_DEFAULT_JIRA_ARMATIS_USER_ID: str = config("RAID_DEFAULT_JIRA_ARMATIS_USER_ID")
RAID_DEFAULT_JIRA_NEXUS_USER_ID: str = config("RAID_DEFAULT_JIRA_NEXUS_USER_ID")
RAID_DEFAULT_JIRA_ADM_USER_ID: str = config("RAID_DEFAULT_JIRA_ADM_USER_ID")
RAID_JIRA_API_USER: str = config("RAID_JIRA_API_USER")
RAID_JIRA_API_PASSWORD: str = config("RAID_JIRA_API_PASSWORD")
RAID_LEGACY_MS_REST_API_KEY: str = config("RAID_LEGACY_MS_REST_API_KEY")
RAID_JIRA_API_PROTOCOL: str = config("RAID_JIRA_API_PROTOCOL")
RAID_JIRA_API_URL: str = config("RAID_JIRA_API_URL")
RAID_JIRA_API_VERSION: str = config("RAID_JIRA_API_VERSION")
RAID_JIRA_PROJECT_KEY: str = config("RAID_JIRA_PROJECT_KEY")
RAID_BASE_URL_API: str = config("RAID_BASE_URL_API")
RAID_QUALIFIER_URL: str = config("RAID_QUALIFIER_URL")

RAID_JIRA_USER_IDS: dict[str, str] = {
    "admvalue.com": RAID_DEFAULT_JIRA_ADM_USER_ID,
    "nexuscontactcenter.com": RAID_DEFAULT_JIRA_NEXUS_USER_ID,
    "armatis.com": RAID_DEFAULT_JIRA_ARMATIS_USER_ID,
    "armatis.jira": RAID_DEFAULT_JIRA_ARMATIS_USER_ID,
    "armatis-lc.com": RAID_DEFAULT_JIRA_ARMATIS_USER_ID,
    "manomano.com": RAID_DEFAULT_JIRA_QRAFT_USER_ID,
}
